name: Deploy App

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # port: ${{ secrets.EC2_PORT }}
          script: |
            cd ~/4-Moving-Team1-BE 
            git pull origin develop
            npm ci
            pm2 restart 0
            pm2 status
            pm2 save
