name: Daily Estimate Status Update

on:
  schedule:
    - cron: "0 0 * * *" # 매일 KST 오전 9시 실행

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Run Scheduler on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/4-Moving-Team1-BE
            git pull origin develop
            npm run build
            npm ci
            node dist/utils/scheduler.js
